version: '3.8'

services:
  finance-app:
    build: .
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
    env_file:
      - .env
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./logs:/var/www/html/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
